#lang info
(define install-collection "installer.rkt")
(define collection "racket-mupdf")
(define deps '("base"))
(define build-deps '("scribble-lib" "racket-doc" "rackunit-lib"))
(define scribblings '(("scribblings/racket-mupdf.scrbl" ())))
(define pkg-desc "Description Here")
(define version "0.0")
(define pkg-authors '(zhanghao))
(define license '(Apache-2.0 OR MIT))
